proposta-api:
  exchange-name:
    proposta-pendente: 'proposta-pendente.ex'
  queue-name:
    proposta-pendente-analise-credito: 'proposta-pendente.ms-analise-credito'
    proposta-pendente-notificacao: 'proposta-pendente.ms-notificacao'
    proposta-concluida-proposta: 'proposta-concluida.ms-proposta'
    proposta-concluida-notificacao: 'proposta-concluida.ms-notificacao'

---
spring:
  application:
    name: proposta-api
#  datasource:
#    url: jdbc:postgresql://localhost:5432/proposta
#    password: secret
#    username: myuser
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
  docker:
    compose:
      enabled: true
      file: src/main/resources/compose.yaml
---
logging:
  level:
    org.springframework.jdbc: DEBUG
